package server

import (
	"context"
	"time"

	api "github.com/MatsuoTakuro/proglog/api/v1"
	"github.com/MatsuoTakuro/proglog/internal/auth"
	"github.com/MatsuoTakuro/proglog/internal/server/middleware"
	"go.opencensus.io/plugin/ocgrpc"

	grpc_middleware "github.com/grpc-ecosystem/go-grpc-middleware"
	grpc_auth "github.com/grpc-ecosystem/go-grpc-middleware/auth"
	grpc_zap "github.com/grpc-ecosystem/go-grpc-middleware/logging/zap"
	grpc_ctxtags "github.com/grpc-ecosystem/go-grpc-middleware/tags"

	"google.golang.org/grpc"
)

// items that matchs ones in ACL policy table
const (
	objectWildcard = "*"
	produceAction  = "produce"
	consumeAction  = "consume"
)

// grpcServer implements api.LogServer generated by copiling with grpc plugin
type grpcServer struct {
	api.UnimplementedLogServer
	*Config
}

var _ api.LogServer = (*grpcServer)(nil)

// abstract log behavior as an interface
type CommitLog interface {
	Append(*api.Record) (uint64, error)
	Read(uint64) (*api.Record, error)
}

// abstract authorizer behavior as an interface
type Authorizer interface {
	Authorize(subject, object, action string) error
}

// Config is a config for a grpc server
type Config struct {
	CommitLog  CommitLog  // embedded interface. this reverses server dependencies on log implementations
	Authorizer Authorizer // embedded interface. this reverses server dependencies on authorizer implementations
}

func NewGRPCServer(cfg *Config, grpcOpts ...grpc.ServerOption) (
	*grpc.Server, error,
) {
	logger, logOpts := middleware.NewSrvLogger()

	err := middleware.SetMetricsAndTracer()
	if err != nil {
		return nil, err
	}

	grpcOpts = append(grpcOpts,
		grpc.StreamInterceptor(
			grpc_middleware.ChainStreamServer(
				grpc_ctxtags.StreamServerInterceptor(), // for tracing
				grpc_zap.StreamServerInterceptor(logger, logOpts...),
				grpc_auth.StreamServerInterceptor(middleware.Authenticate),
			),
		),
		grpc.UnaryInterceptor(
			grpc_middleware.ChainUnaryServer(
				grpc_ctxtags.UnaryServerInterceptor(), // for tracing
				grpc_zap.UnaryServerInterceptor(logger, logOpts...),
				grpc_auth.UnaryServerInterceptor(middleware.Authenticate),
			),
		),
		// for metrics to collect data as stats
		grpc.StatsHandler(&ocgrpc.ServerHandler{}),
	)

	gsrv := grpc.NewServer(grpcOpts...)
	srv, err := newGRPCServer(cfg)
	if err != nil {
		return nil, err
	}
	api.RegisterLogServer(gsrv, srv)

	return gsrv, nil
}

func newGRPCServer(cfg *Config) (srv *grpcServer, err error) {
	srv = &grpcServer{
		Config: cfg,
	}

	return srv, nil
}

func (s *grpcServer) Produce(ctx context.Context, req *api.ProduceRequest) (
	*api.ProduceResponse, error,
) {
	if err := s.Authorizer.Authorize(
		auth.Subject(ctx),
		objectWildcard,
		produceAction,
	); err != nil {
		return nil, err
	}

	off, err := s.CommitLog.Append(req.Record)
	if err != nil {
		return nil, err
	}

	return &api.ProduceResponse{
		Offset: off,
	}, nil
}

func (s *grpcServer) Consume(ctx context.Context, req *api.ConsumeRequest) (
	*api.ConsumeResponse, error,
) {
	if err := s.Authorizer.Authorize(
		auth.Subject(ctx),
		objectWildcard,
		produceAction,
	); err != nil {
		return nil, err
	}

	record, err := s.CommitLog.Read(req.Offset)
	if err != nil {
		return nil, err
	}

	return &api.ConsumeResponse{
		Record: record,
	}, nil
}

// ProduceStream produces record(s) as bi-directional streaming RPC
func (s *grpcServer) ProduceStream(
	stream api.Log_ProduceStreamServer,
) error {
	for {
		req, err := stream.Recv()
		if err != nil {
			return err
		}

		res, err := s.Produce(stream.Context(), req)
		if err != nil {
			return err
		}

		if err = stream.Send(res); err != nil {
			return err
		}
	}
}

// ConsumeStream comsumes record(s) as server side streaming RPC
func (s *grpcServer) ConsumeStream(
	req *api.ConsumeRequest,
	stream api.Log_ConsumeStreamServer,
) error {
	for {
		select {
		// notified that streaming is canceled or stopped from a client
		case <-stream.Context().Done():
			return nil

		default:
			// consume a record with a given offset
			res, err := s.Consume(stream.Context(), req)
			switch err.(type) {
			// consume a record sucessfully and will send it back to a client
			case nil:

			// in case of completing consumption of records with a given offset,
			// wait for new entry of a record.
			case api.ErrOffsetOutOfRange:
				time.Sleep(time.Second)
				continue

			// fails to consume a record
			default:
				return err
			}

			// send a record in streaming
			if err = stream.Send(res); err != nil {
				return err
			}

			// try to consume the next record
			req.Offset++
		}
	}
}
